### ISSUE TITLE
CID 写死不会过期吗？

### ISSUE THREAD

**Issue by leavez** [laoshufeifei/beijing_real_time_bus#1]
试过把 App 删了重装之后，header 中的 CID 会变化

**Comment by laoshufeifei** [comment]
这个CID是从 APK 里扒出来的，而且我把“北京实时公交” 卸载了重新安装，抓取了一下，发现 CID 没有变。 而且 “北京交通” APK 的接口也是这个CID。

这个哥们更牛逼，做了个小程序，他的CID也是这个
https://github.com/xuebing1110/rtbus
