### ISSUE TITLE
你好，小白一枚，请问一下如何知道这个数据接口的呢？

### ISSUE THREAD

**Issue by windxgg** [laoshufeifei/beijing_real_time_bus#2]
在HTML源码里没有发现ajax_rtbus_data.php的字样

**Comment by laoshufeifei** [comment]
用 chrome 或者 firefox 打开 调试模式，在 network 选项卡里，选上 “Presever log”，然后正常操作就能看到有用的接口。

**Comment by windxgg** [comment]
好的，谢谢
